services:
  backend:
    build: 
      context: ./backend
      args:
        DB_URI: ${DB_URI}
    environment:
      DB_URI: ${DB_URI}
    ports:
      - "5000:5000"
    networks:
      - webnet

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_NODE_ENV: ${VITE_NODE_ENV}
        VITE_API_URL_DEV: ${VITE_API_URL_DEV}
        VITE_API_PORT_DEV: ${VITE_API_PORT_DEV}
        VITE_API_URL_PROD: ${VITE_API_URL_PROD}
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
        VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID}
    environment:
      VITE_NODE_ENV: ${VITE_NODE_ENV}
      VITE_API_URL_DEV: ${VITE_API_URL_DEV}
      VITE_API_PORT_DEV: ${VITE_API_PORT_DEV}
      VITE_API_URL_PROD: ${VITE_API_URL_PROD}
      VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
      VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
      VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
      VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID}
    ports: 
      - "8080:80"
    depends_on:
      - backend
    networks:
      - webnet

networks:
  webnet: