services:
  backend:
    image: reyesjl/yhtreviews-backend:latest
    environment:
      DB_URI: ${DB_URI}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "5000:5000"
    networks:
      - webnet

  frontend:
    image: reyesjl/yhtreviews-frontend:latest
    environment:
      BUILD_ENV: ${BUILD_ENV}
      VITE_NODE_ENV: ${VITE_NODE_ENV}
      VITE_API_URL_DEV: ${VITE_API_URL_DEV}
      VITE_API_PORT_DEV: ${VITE_API_PORT_DEV}
      VITE_API_URL_PROD: ${VITE_API_URL_PROD}
      VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
      VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
      VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
      VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID}
    ports: 
      - "8080:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - webnet
    volumes:
      - ./ssl/nginx.crt:/etc/nginx/ssl/nginx.crt:ro
      - ./ssl/nginx.key:/etc/nginx/ssl/nginx.key:ro

networks:
  webnet: